### ISSUE TITLE
Software development for HWACHA

### ISSUE THREAD

**Issue by aignacio** [ucb-bar/hwacha-template#4]
Hi everyone from Hwacha team,
Thanks for sharing this template for Hwacha!, I'm starting to test your repository and after a cloning and building the default configuration (**ISCA2016Config**) the emulator has been generated with the name **simulator-freechips.rocketchip.system-ExampleHwachaConfig** what I suppose that's right. So, what's template software code for generating code for such target? I was trying to run a dhrystone benchmark on the target and it did not work, as other programs that I have been using from the official [riscv-tests](https://github.com/riscv/riscv-tests).
![screenshot from 2019-02-25 10-57-59](https://user-images.githubusercontent.com/5991372/53329388-44d8b180-38ec-11e9-8e38-1b81808f6521.png)
Can you provide a simple step or point up the right repo to use as base for software development for HWACHA? I tried to build [esp-tests](https://github.com/ucb-bar/esp-tests) also and I couldn't get it, because the custom instructions were not recognized by the toolchain.

**Comment by a0u** [comment]
The Hwacha port of the GNU toolchain can be built from the [esp-tools](https://github.com/ucb-bar/esp-tools) meta-repo, which is included as a submodule in hwacha-template.  See the "Getting Started" section of the [README](README.md).

**Comment by aignacio** [comment]
@a0u thanks!, I was clicking on the link on the README.md but it's pointing to a broken link (ends with /**riscv**/esp-tools) and I didn't search for the right one....

**Comment by a0u** [comment]
> I was clicking on the link on the README.md but it's pointing to a broken link

Fixed by 7b07d9033df5962538e741e839798657f1716d17 - thanks for the catch.
