### ISSUE TITLE
make doesn't work

### ISSUE THREAD

**Issue by GhostScreaming** [ucb-bar/hwacha-template#6]
Hi all, thanks for your sharing hwacha template.
After cloning and building risc-v tools, I try to run `make` in verisim, but an unexpected error occured.
```
make: *** No rule to make target '/home/mine/workspace/test_workspace/hwacha-template/verisim/generated-src/firrtl_black_box_resource_files.top.f', needed by '/home/mine/workspace/test_workspace/hwacha-template/verisim/generated-src/freechips.rocketchip.system.ExampleHwachaConfig.harness.v'.  Stop.
make: *** Waiting for unfinished jobs....
```
What's more, I changed JVM_HEAP_SIZE in Makefrag-variables to 2G, otherwise the JVM virtual machine can't be created. Everything runs as expeccted except the mentioned problem. Only a folder named generated-src with some files inside was generated. But **simulator-freechips.rocketchip.system-ExampleHwachaConfig** hasn't been created.
Howerver, I can't figure out where the problem is. Could you do me a favor? Thanks!

**Comment by colinschmidt** [comment]
There is probably an earlier error message. I'd guess you haven't initialized the git submodules, so barstools can't be run to generate the black box resource file.

**Comment by GhostScreaming** [comment]
I've run init-submodules after cloning the repo. May be any other reason?

**Comment by colinschmidt** [comment]
You'll have to post the rest of the error message then. Maybe as a [gist](https://gist.github.com)?

**Comment by GhostScreaming** [comment]
I've created a [gist](https://gist.github.com/GhostScreaming/3a7342292a76292bd0082f3b1f2eb46b).
Thanks for your help!

**Comment by colinschmidt** [comment]
Can you try not running make in parallel? Based on the output it looks like its running in parallel and we may be missing a dependency in the makefile such that it thinks it can do more at once then it truly can. If you force it to be serial it should avoid this issue. If we can confirm thats the issue then we can look into fixing the Makefile.
